// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


import Foundation
import CCXT

public class Alpaca: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "alpaca", config: config)
    }
}

public class Apex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "apex", config: config)
    }
}

public class Ascendex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "ascendex", config: config)
    }
}

public class Bequant: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bequant", config: config)
    }
}

public class Bigone: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bigone", config: config)
    }
}

public class Binance: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "binance", config: config)
    }
}

public class Binancecoinm: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "binancecoinm", config: config)
    }
}

public class Binanceus: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "binanceus", config: config)
    }
}

public class Binanceusdm: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "binanceusdm", config: config)
    }
}

public class Bingx: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bingx", config: config)
    }
}

public class Bit2c: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bit2c", config: config)
    }
}

public class Bitbank: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitbank", config: config)
    }
}

public class Bitbns: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitbns", config: config)
    }
}

public class Bitfinex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitfinex", config: config)
    }
}

public class Bitflyer: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitflyer", config: config)
    }
}

public class Bitget: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitget", config: config)
    }
}

public class Bithumb: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bithumb", config: config)
    }
}

public class Bitmart: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitmart", config: config)
    }
}

public class Bitmex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitmex", config: config)
    }
}

public class Bitopro: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitopro", config: config)
    }
}

public class Bitrue: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitrue", config: config)
    }
}

public class Bitso: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitso", config: config)
    }
}

public class Bitstamp: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitstamp", config: config)
    }
}

public class Bitteam: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitteam", config: config)
    }
}

public class Bittrade: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bittrade", config: config)
    }
}

public class Bitvavo: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bitvavo", config: config)
    }
}

public class Blockchaincom: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "blockchaincom", config: config)
    }
}

public class Blofin: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "blofin", config: config)
    }
}

public class Btcalpha: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "btcalpha", config: config)
    }
}

public class Btcbox: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "btcbox", config: config)
    }
}

public class Btcmarkets: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "btcmarkets", config: config)
    }
}

public class Btcturk: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "btcturk", config: config)
    }
}

public class Bybit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "bybit", config: config)
    }
}

public class Cex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "cex", config: config)
    }
}

public class Coinbase: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinbase", config: config)
    }
}

public class Coinbaseadvanced: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinbaseadvanced", config: config)
    }
}

public class Coinbaseexchange: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinbaseexchange", config: config)
    }
}

public class Coinbaseinternational: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinbaseinternational", config: config)
    }
}

public class Coincatch: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coincatch", config: config)
    }
}

public class Coincheck: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coincheck", config: config)
    }
}

public class Coinex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinex", config: config)
    }
}

public class Coinmate: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinmate", config: config)
    }
}

public class Coinmetro: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinmetro", config: config)
    }
}

public class Coinone: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinone", config: config)
    }
}

public class Coinsph: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinsph", config: config)
    }
}

public class Coinspot: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "coinspot", config: config)
    }
}

public class Cryptocom: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "cryptocom", config: config)
    }
}

public class Cryptomus: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "cryptomus", config: config)
    }
}

public class Defx: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "defx", config: config)
    }
}

public class Delta: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "delta", config: config)
    }
}

public class Deribit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "deribit", config: config)
    }
}

public class Derive: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "derive", config: config)
    }
}

public class Digifinex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "digifinex", config: config)
    }
}

public class Exmo: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "exmo", config: config)
    }
}

public class Fmfwio: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "fmfwio", config: config)
    }
}

public class Foxbit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "foxbit", config: config)
    }
}

public class Gate: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "gate", config: config)
    }
}

public class Gateio: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "gateio", config: config)
    }
}

public class Gemini: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "gemini", config: config)
    }
}

public class Hashkey: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "hashkey", config: config)
    }
}

public class Hibachi: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "hibachi", config: config)
    }
}

public class Hitbtc: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "hitbtc", config: config)
    }
}

public class Hollaex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "hollaex", config: config)
    }
}

public class Htx: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "htx", config: config)
    }
}

public class Huobi: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "huobi", config: config)
    }
}

public class Hyperliquid: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "hyperliquid", config: config)
    }
}

public class Independentreserve: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "independentreserve", config: config)
    }
}

public class Indodax: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "indodax", config: config)
    }
}

public class Kraken: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "kraken", config: config)
    }
}

public class Krakenfutures: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "krakenfutures", config: config)
    }
}

public class Kucoin: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "kucoin", config: config)
    }
}

public class Kucoinfutures: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "kucoinfutures", config: config)
    }
}

public class Latoken: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "latoken", config: config)
    }
}

public class Lbank: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "lbank", config: config)
    }
}

public class Luno: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "luno", config: config)
    }
}

public class Mercado: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "mercado", config: config)
    }
}

public class Mexc: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "mexc", config: config)
    }
}

public class Modetrade: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "modetrade", config: config)
    }
}

public class Myokx: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "myokx", config: config)
    }
}

public class Ndax: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "ndax", config: config)
    }
}

public class Novadax: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "novadax", config: config)
    }
}

public class Oceanex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "oceanex", config: config)
    }
}

public class Okcoin: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "okcoin", config: config)
    }
}

public class Okx: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "okx", config: config)
    }
}

public class Okxus: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "okxus", config: config)
    }
}

public class Onetrading: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "onetrading", config: config)
    }
}

public class Oxfun: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "oxfun", config: config)
    }
}

public class P2b: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "p2b", config: config)
    }
}

public class Paradex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "paradex", config: config)
    }
}

public class Paymium: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "paymium", config: config)
    }
}

public class Phemex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "phemex", config: config)
    }
}

public class Poloniex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "poloniex", config: config)
    }
}

public class Probit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "probit", config: config)
    }
}

public class Timex: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "timex", config: config)
    }
}

public class Tokocrypto: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "tokocrypto", config: config)
    }
}

public class Tradeogre: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "tradeogre", config: config)
    }
}

public class Upbit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "upbit", config: config)
    }
}

public class Wavesexchange: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "wavesexchange", config: config)
    }
}

public class Whitebit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "whitebit", config: config)
    }
}

public class Woo: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "woo", config: config)
    }
}

public class Woofipro: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "woofipro", config: config)
    }
}

public class Xt: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "xt", config: config)
    }
}

public class Yobit: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "yobit", config: config)
    }
}

public class Zaif: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "zaif", config: config)
    }
}

public class Zonda: Exchange {
    public init?(config: [String: Any]? = nil) {
        super.init(exchangeName: "zonda", config: config)
    }
}
