// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


public typealias Strings = [String]?
public typealias Num = Double?
public typealias IndexType = Any
public typealias OrderSide = String?
public typealias OrderType = String
public typealias MarketType = String
public typealias SubType = String?
public typealias NullableDict = [String: Any]?
public typealias NullableList = [Any]?
public struct MinMax {
    public var min: Double?
    public var max: Double?
}
public struct FeeInterface {
    public var currency: String?
    public var cost: Double?
    public var rate: Double?
}
public struct TradingFeeInterface {
    public var info: Any
    public var symbol: String?
    public var maker: Double?
    public var taker: Double?
    public var percentage: Bool?
    public var tierBased: Bool?
}
public typealias Fee = FeeInterface?
public struct MarketMarginModes {
    public var isolated: Bool
    public var cross: Bool
}
public struct MarketInterface {
    public var id: String?
    public var numericId: Double?
    public var uppercaseId: String?
    public var lowercaseId: String?
    public var symbol: String
    public var base: String
    public var quote: String
    public var baseId: String?
    public var quoteId: String?
    public var active: Bool?
    public var type: String
    public var subType: String?
    public var spot: Bool
    public var margin: Bool
    public var swap: Bool
    public var future: Bool
    public var option: Bool
    public var contract: Bool
    public var settle: String?
    public var settleId: String?
    public var contractSize: Double?
    public var linear: Bool?
    public var inverse: Bool?
    public var quanto: Bool
    public var expiry: Int?
    public var expiryDatetime: String?
    public var strike: Double?
    public var optionType: String?
    public var taker: Double?
    public var maker: Double?
    public var percentage: Bool?
    public var tierBased: Bool?
    public var feeSide: String?
    public var precision: Precision
    public struct Precision {
        public var amount: Double?
        public var price: Double?
        public var cost: Double?
    }
    public var marginModes: MarketMarginModes
    public var limits: Limits
    public struct Limits {
        public var amount: MinMax
        public var cost: MinMax
        public var leverage: MinMax
        public var price: MinMax
        public var market: MinMax
    }
    public var created: Int?
    public var info: Any
}
public struct Trade {
    public var fee: Fee
}
public struct Order {
    public var id: String
    public var clientOrderId: String?
    public var datetime: String
    public var timestamp: Double
    public var lastTradeTimestamp: Double
    public var lastUpdateTimestamp: Double
    public var status: String
    public var symbol: String
    public var type: String?
    public var timeInForce: String?
    public var side: String
    public var price: Double
    public var average: Double
    public var amount: Double
    public var filled: Double
    public var remaining: Double
    public var stopPrice: Double
    public var triggerPrice: Double
    public var takeProfitPrice: Double
    public var stopLossPrice: Double
    public var cost: Double
    public var trades: [Trade]
    public var fee: Fee
    public var reduceOnly: Bool?
    public var postOnly: Bool?
    public var info: Any
}
public struct OrderBook {
    public var datetime: String?
    public var timestamp: Int?
    public var nonce: Int?
    public var symbol: String?
}
public typealias OrderBooks = [String: OrderBook]
public struct Ticker {
    public var symbol: String
    public var info: Any
    public var timestamp: Int?
    public var datetime: String?
    public var high: Double?
    public var low: Double?
    public var bid: Double?
    public var bidVolume: Double?
    public var ask: Double?
    public var askVolume: Double?
    public var vwap: Double?
    public var open: Double?
    public var close: Double?
    public var last: Double?
    public var previousClose: Double?
    public var change: Double?
    public var percentage: Double?
    public var average: Double?
    public var quoteVolume: Double?
    public var baseVolume: Double?
    public var indexPrice: Double?
    public var markPrice: Double?
}
public struct Transaction {
    public var info: Any
    public var id: String?
    public var txid: String?
    public var timestamp: Int?
    public var datetime: String?
    public var address: String?
    public var addressFrom: String?
    public var addressTo: String?
    public var tag: String?
    public var tagFrom: String?
    public var tagTo: String?
    public var type: String
    public var amount: Double?
    public var currency: String?
    public var status: String
    public var updated: Int?
    public var fee: Fee
    public var network: String?
    public var comment: String?
    public var isInternal: Bool?
}
public typealias Tickers = [String: Ticker]
public struct CurrencyInterface {
    public var id: String
    public var code: String
    public var numericId: Int?
    public var precision: Double
    public var type: String?
    public var margin: Bool?
    public var name: String?
    public var active: Bool?
    public var deposit: Bool?
    public var withdraw: Bool?
    public var fee: Double?
    public var limits: Limits
    public struct Limits {
        public var amount: Amount
        public struct Amount {
            public var min: Double?
            public var max: Double?
        }
        public var withdraw: Withdraw
        public struct Withdraw {
            public var min: Double?
            public var max: Double?
        }
    }
    public var networks: Networks
    public struct Networks {
        public var string: Any
    }
    public var info: Any
}
public struct Balance {
    public var free: Double?
    public var used: Double?
    public var total: Double?
    public var debt: Double?
}
public struct BalanceAccount {
    public var free: String?
    public var used: String?
    public var total: String?
}
public struct Account {
    public var id: String?
    public var type: String?
    public var code: String?
    public var info: Any
}
public typealias PartialBalances = [String: Double]
public typealias Balances = [String: Balance]
public struct DepositAddress {
    public var info: Any
    public var currency: String
    public var network: String
    public var address: String
    public var tag: String?
}
public struct WithdrawalResponse {
    public var info: Any
    public var id: String
}
public struct FundingRate {
    public var symbol: String
    public var info: Any
    public var timestamp: Double
    public var fundingRate: Double
    public var datetime: String
    public var markPrice: Double
    public var indexPrice: Double
    public var interestRate: Double
    public var estimatedSettlePrice: Double
    public var fundingTimestamp: Double
    public var fundingDatetime: String
    public var nextFundingTimestamp: Double
    public var nextFundingDatetime: String
    public var nextFundingRate: Double
    public var previousFundingTimestamp: Double
    public var previousFundingDatetime: String
    public var previousFundingRate: Double
    public var interval: String
}
public typealias FundingRates = [String: FundingRate]
public struct Position {
    public var symbol: String
    public var id: String?
    public var info: Any
    public var timestamp: Double
    public var datetime: String
    public var contracts: Double
    public var contractSize: Double
    public var side: String?
    public var notional: Double
    public var leverage: Double
    public var unrealizedPnl: Double
    public var realizedPnl: Double
    public var collateral: Double
    public var entryPrice: Double
    public var markPrice: Double
    public var liquidationPrice: Double
    public var marginMode: String?
    public var hedged: Bool
    public var maintenanceMargin: Double
    public var maintenanceMarginPercentage: Double
    public var initialMargin: Double
    public var initialMarginPercentage: Double
    public var marginRatio: Double
    public var lastUpdateTimestamp: Double
    public var lastPrice: Double
    public var stopLossPrice: Double
    public var takeProfitPrice: Double
    public var percentage: Double
}
public struct BorrowInterest {
    public var info: Any
    public var symbol: String?
    public var currency: String?
    public var interest: Double
    public var interestRate: Double
    public var amountBorrowed: Double
    public var marginMode: String?
    public var timestamp: Int?
    public var datetime: String?
}
public struct LeverageTier {
    public var tier: Double
    public var symbol: String?
    public var currency: String?
    public var minNotional: Double
    public var maxNotional: Double
    public var maintenanceMarginRate: Double
    public var maxLeverage: Double
    public var info: Any
}
public struct LedgerEntry {
    public var info: Any
    public var id: String?
    public var timestamp: Double
    public var datetime: String?
    public var direction: String?
    public var account: String?
    public var referenceId: String?
    public var referenceAccount: String?
    public var type: String?
    public var currency: String?
    public var amount: Double
    public var before: Double
    public var after: Double
    public var status: String?
    public var fee: Fee
}
public struct DepositWithdrawFeeNetwork {
    public var fee: Double
    public var percentage: Bool
}
public struct DepositWithdrawFee {
    public var info: Any
    public var withdraw: DepositWithdrawFeeNetwork
    public var deposit: DepositWithdrawFeeNetwork
    public var networks: [String: DepositWithdrawFeeNetwork]
}
public struct TransferEntry {
    public var info: Any
    public var id: String?
    public var timestamp: Double
    public var datetime: String?
    public var currency: String?
    public var amount: Double
    public var fromAccount: String?
    public var toAccount: String?
    public var status: String?
}
public struct CrossBorrowRate {
    public var info: Any
    public var currency: String?
    public var rate: Double
    public var period: Double
    public var timestamp: Double
    public var datetime: String?
}
public struct IsolatedBorrowRate {
    public var info: Any
    public var symbol: String
    public var base: String
    public var baseRate: Double
    public var quote: String
    public var quoteRate: Double
    public var period: Int?
    public var timestamp: Int?
    public var datetime: String?
}
public struct FundingRateHistory {
    public var info: Any
    public var symbol: String
    public var fundingRate: Double
    public var timestamp: Double
    public var datetime: String?
}
public struct OpenInterest {
    public var symbol: String
    public var openInterestAmount: Double
    public var openInterestValue: Double
    public var baseVolume: Double
    public var quoteVolume: Double
    public var timestamp: Double
    public var datetime: String?
    public var info: Any
}
public typealias OpenInterests = [String: OpenInterest]
public struct Liquidation {
    public var info: Any
    public var symbol: String
    public var timestamp: Double
    public var datetime: String?
    public var price: Double
    public var baseValue: Double
    public var quoteValue: Double
    public var side: String?
}
public struct OrderRequest {
    public var symbol: String
    public var type: String
    public var side: String?
    public var amount: Double
    public var price: Double?
    public var params: Any
}
public struct CancellationRequest {
    public var id: String
    public var clientOrderId: String
    public var symbol: String
}
public struct FundingHistory {
    public var info: Any
    public var symbol: String
    public var code: String
    public var timestamp: Double
    public var datetime: String?
    public var id: String
    public var amount: Double
}
public struct MarginMode {
    public var info: Any
    public var symbol: String
    public var marginMode: String
}
public struct Greeks {
    public var symbol: String
    public var timestamp: Double
    public var datetime: String?
    public var delta: Double
    public var gamma: Double
    public var theta: Double
    public var vega: Double
    public var rho: Double
    public var vanna: Double
    public var volga: Double
    public var charm: Double
    public var bidSize: Double
    public var askSize: Double
    public var bidImpliedVolatility: Double
    public var askImpliedVolatility: Double
    public var markImpliedVolatility: Double
    public var bidPrice: Double
    public var askPrice: Double
    public var markPrice: Double
    public var lastPrice: Double
    public var underlyingPrice: Double
    public var info: Any
}
public struct Conversion {
    public var info: Any
    public var timestamp: Double
    public var datetime: String
    public var id: String
    public var fromCurrency: String
    public var fromAmount: Double
    public var toCurrency: String
    public var toAmount: Double
    public var price: Double
    public var fee: Double
}
public struct Option {
    public var info: Any
    public var currency: String
    public var symbol: String
    public var timestamp: Double
    public var datetime: String?
    public var impliedVolatility: Double
    public var openInterest: Double
    public var bidPrice: Double
    public var askPrice: Double
    public var midPrice: Double
    public var markPrice: Double
    public var lastPrice: Double
    public var underlyingPrice: Double
    public var change: Double
    public var percentage: Double
    public var baseVolume: Double
    public var quoteVolume: Double
}
public struct LastPrice {
    public var symbol: String
    public var timestamp: Double
    public var datetime: String
    public var price: Double
    public var side: String?
    public var info: Any
}
public struct Leverage {
    public var info: Any
    public var symbol: String
    public var marginMode: String
    public var longLeverage: Double
    public var shortLeverage: Double
}
public struct LongShortRatio {
    public var info: Any
    public var symbol: String
    public var timestamp: Double
    public var datetime: String
    public var timeframe: String
    public var longShortRatio: Double
}
public struct MarginModification {
    public var info: Any
    public var symbol: String
    public var type: String?
    public var marginMode: String?
    public var amount: Double?
    public var total: Double?
    public var code: String?
    public var status: String?
    public var timestamp: Int?
    public var datetime: String?
}
public typealias Leverages = [String: Leverage]
public typealias LastPrices = [String: LastPrice]
public typealias Currencies = [String: CurrencyInterface]
public typealias TradingFees = [String: TradingFeeInterface]
public typealias MarginModes = [String: MarginMode]
public typealias OptionChain = [String: Option]
public typealias IsolatedBorrowRates = [String: IsolatedBorrowRate]
public typealias CrossBorrowRates = [String: CrossBorrowRate]
public typealias LeverageTiers = [String: [LeverageTier]]
public typealias OHLCV = (Double?, Double?, Double?, Double?, Double?, Double?)
public typealias OHLCVC = (Double?, Double?, Double?, Double?, Double?, Double?, Double?)
public typealias implicitReturnType = Any
public typealias Market = MarketInterface?
public typealias Currency = CurrencyInterface?
public struct BaseConstructorArgs {
    public var apiKey: String
    public var secret: String
    public var password: String
    public var privateKey: String
    public var walletAddress: String
    public var uid: String
    public var verbose: Bool
    public var testnet: Bool
    public var options: [String: Any]
    public var enableRateLimit: Bool
    public var httpsProxy: String
    public var socksProxy: String
    public var wssProxy: String
    public var proxy: String
    public var rateLimit: Double
    public var commonCurrencies: [String: Any]
    public var userAgent: String
    public var userAgents: [String: Any]
    public var timeout: Double
    public var markets: [String: Any]
    public var currencies: [String: Any]
    public var hostname: String
    public var urls: [String: Any]
    public var headers: [String: Any]
}
public typealias ConstructorArgs = BaseConstructorArgs
